### ISSUE TITLE
Can't put the devices into sleep mode

### ISSUE THREAD

**Issue by Combinator78** [UpstreamData/pyasic#259]
S19K Pro (Stock): 192.168.218.24
Traceback (most recent call last):
  File "C:\vekus\agent\test.py", line 18, in <module>
    asyncio.run(main())
  File "C:\Users\User90\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\User90\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User90\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\vekus\agent\test.py", line 14, in main
    print("Shut down:", await miner.stop_mining())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\vekus\agent\local_libs\pyasic\miners\backends\antminer.py", line 187, in stop_mining
    cfg.miner_mode = MiningModeConfig.sleep()
    ^^^^^^^^^^^^^^
  File "C:\Users\User90\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic\main.py", line 926, in __setattr__
    raise ValueError(f'"{self.__class__.__name__}" object has no field "{name}"')
ValueError: "MinerConfig" object has no field "miner_mode"

```
import asyncio  # asyncio for handling the async part
import sys
sys.path.append('local_libs')
import pyasic

IP = "192.168.218.24"
async def main():
    miner = await pyasic.get_miner(IP)
    print(miner)
    print("Shut down:", await miner.stop_mining())
if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by b-rowan** [comment]
Fixed in 0.67.3
