### ISSUE TITLE
Partially supported miner found: M50S++VL30

### ISSUE THREAD

**Issue by Combinator78** [UpstreamData/pyasic#261]
C:\vekus\agent1\local_libs\pyasic\miners\factory.py:883: UserWarning: Partially supported miner found: M50S++VL30, type: MinerTypes.WHATSMINER, please open an issue with miner data and this model on GitHub (https://github.com/UpstreamData/pyasic/issues).
  warnings.warn(
Traceback (most recent call last):
  File "C:\vekus\agent1\local_libs\pyasic\miners\base.py", line 524, in _get_data
    miner_data[data_name] = await function(**args_to_send)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\vekus\agent1\local_libs\pyasic\miners\backends\btminer.py", line 407, in _get_hashrate
    return self.algo.hashrate(
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'hashrate'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\vekus\agent1\test.py", line 18, in <module>
    asyncio.run(gather_miner_data())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nomed\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\nomed\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nomed\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\vekus\agent1\test.py", line 12, in gather_miner_data
    miner_data = await miner.get_data()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\vekus\agent1\local_libs\pyasic\miners\base.py", line 567, in get_data
    gathered_data = await self._get_data(
                    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\vekus\agent1\local_libs\pyasic\miners\base.py", line 526, in _get_data
    raise APIError(
pyasic.errors.APIError: Failed to call hashrate on WhatsMiner (Stock): 172.16.21.23 while getting data.

**Comment by b-rowan** [comment]
Should be supported now.
